###############################################################################
<#
.SYNOPSIS
Generates and executes PowerShell commands using AI assistance.

.DESCRIPTION
Uses AI models to generate PowerShell commands based on
natural language queries. The function can either send commands directly to
the PowerShell window or copy them to the clipboard. It leverages AI models
to interpret natural language and convert it into executable PowerShell
commands with comprehensive parameter support for various AI backends.

SECURITY NOTE: This function executes commands generated by AI models.
By default, it validates commands against a safety whitelist before execution.
Only read-only and non-destructive cmdlets are allowed.
#>
function Invoke-AIPowershellCommand {

    [CmdletBinding()]
    [OutputType([void])]
    [Alias('hint')]
    param (
        [Parameter(Position = 0, Mandatory = $true, HelpMessage = 'The natural language query to generate a command for')]
        [ValidateNotNullOrEmpty()]
        [string] $PowershellCmdline,

        [Parameter(Mandatory = $false, HelpMessage = 'The type of LLM query')]
        [ValidateSet('SimpleIntelligence','Knowledge','Pictures','TextTranslation','Coding','ToolUse')]
        [string] $LLMQueryType = 'Coding',

        [Parameter(Mandatory = $false, HelpMessage = 'The model identifier or pattern to use for AI operations')]
        [string] $Model,

        [Parameter(Mandatory = $false, HelpMessage = 'The API endpoint URL for AI operations')]
        [string] $ApiEndpoint,

        [Parameter(Mandatory = $false, HelpMessage = 'The API key for authenticated AI operations')]
        [string] $ApiKey,

        [Parameter(Mandatory = $false, HelpMessage = 'Launch interactive prompt to configure LLM settings')]
        [switch] $PromptForSettings,

        [Parameter(Mandatory = $false, HelpMessage = 'Indicates that LLM has no support for JSON schemas')]
        [switch] $NoSupportForJsonSchema,

        [Parameter(Mandatory = $false, HelpMessage = 'SECURITY: Enforce whitelist validation before execution (default: $true)')]
        [bool] $EnforceWhitelist = $true,

        [Parameter(Mandatory = $false, HelpMessage = 'Additional safe cmdlet patterns to whitelist')]
        [string[]] $CustomWhitelist = @()
    )

    begin {
        $indexPath = "$($MyInvocation.MyCommand.Module.ModuleBase)\recommended-aitoolset-cmdlets.txt"
        $cmdletIndex = if (Microsoft.PowerShell.Management\Test-Path -LiteralPath $indexPath) {
            Microsoft.PowerShell.Management\Get-Content -LiteralPath $indexPath -Raw -Encoding UTF8
        }
        else {
            ''
        }

        $defaultWhitelist = @(
            'Get-*',
            'Select-Object',
            'Where-Object',
            'Sort-Object',
            'Measure-Object',
            'Format-Table',
            'Format-List',
            'ConvertTo-Json',
            'ConvertFrom-Json',
            'Test-Path',
            'Test-Connection',
            'Resolve-DnsName',
            'Get-ChildItem',
            'Get-Process',
            'Get-Service',
            'Get-Command'
        )

        $safeCommandWhitelist = $defaultWhitelist + $CustomWhitelist

        $ExposedCmdLets = @(
            @{
                Name          = 'Microsoft.PowerShell.Core\Get-Help'
                Description   = 'Retrieves full help for a PowerShell cmdlet including syntax, parameter names, types, and examples.'
                AllowedParams = @('Name=string')
                ForcedParams  = @(@{ Name = 'Full'; Value = $true })
                OutputText    = $true
                Confirm       = $false
            }
        )

        $NoConfirmationToolFunctionNames = @('Get-Help')

        $Instructions = @"

⛔ CRITICAL PROTOCOL — FOLLOW THESE STEPS IN ORDER ⛔

You are generating a PowerShell command to help the user. Follow these steps exactly.

STEP 1 — IS IT A TYPO?
Only apply this if the user message looks like a PowerShell command. If natural language, skip to Step 2.

STEP 2 — SCAN FOR MATCHING CMDLETS:
Below is a list of available GenXdev cmdlets.
$cmdletIndex

STEP 3 — VERIFY PARAMETERS VIA Get-Help:
Use Get-Help to confirm parameter names.

STEP 4 — FALLBACK: GENERAL KNOWLEDGE:
No GenXdev cmdlet fits. Suggest the best standard PowerShell command.

IMPORTANT SECURITY RESTRICTION:
- Only suggest read-only or non-destructive operations.
- NEVER suggest: Remove-Item, Stop-Process, Restart-Computer, Remove-Path, Set-*, New-*, Invoke-Expression, Start-Process with untrusted parameters.
- If the user asks for a destructive operation, refuse and explain why.
"@

        $ResponseFormat = @{
            type        = 'json_schema'
            json_schema = @{
                name   = 'text_transformation_response'
                strict = $true
                schema = @{
                    type       = 'object'
                    properties = @{
                        explanation      = @{ type = 'string'; description = 'explanation what cmdline accomplishes or what is improved to fix the error' }
                        suggestedCmdline = @{ type = 'string'; description = 'The transformed text output' }
                    }
                    required = @('explanation', 'suggestedCmdline')
                }
            }
        } | Microsoft.PowerShell.Utility\ConvertTo-Json -Depth 10

        $invocationParams = GenXdev\Copy-IdenticalParamValues `
            -BoundParameters $PSBoundParameters `
            -FunctionName 'GenXdev\Invoke-LLMQuery' `
            -DefaultValues (Microsoft.PowerShell.Utility\Get-Variable -Scope Local)
    }

    process {
        if (($PowershellCmdline.Trim() -eq '') -or ($PowershellCmdline.Trim() -eq '^U')) {
            return
        }

        $command = GenXdev\Invoke-LLMQuery @invocationParams `
            -Query $PowershellCmdline `
            -Instructions $Instructions `
            -ResponseFormat $ResponseFormat `
            -ExposedCmdLets $ExposedCmdLets `
            -NoConfirmationToolFunctionNames $NoConfirmationToolFunctionNames `
            -Temperature 0.1 `
            -QuietToolChainInvocations

        try {
            $result = $command | Microsoft.PowerShell.Utility\ConvertFrom-Json -ErrorAction Stop
            if (-not $result -or [string]::IsNullOrWhiteSpace($result.suggestedCmdline) -or [string]::IsNullOrWhiteSpace($result.explanation)) {
                throw 'AI response missing required fields'
            }
        }
        catch {
            Microsoft.PowerShell.Utility\Write-Error "'$PowershellCmdline' could not be resolved using AI"
            return
        }

        $explanation = if ($result.explanation.PSObject.Properties['response']) { $result.explanation.response } else { $result.explanation }
        $suggestedCmd = if ($result.suggestedCmdline.PSObject.Properties['response']) { $result.suggestedCmdline.response } else { $result.suggestedCmdline }

        if ([string]::IsNullOrWhiteSpace($suggestedCmd)) {
            Microsoft.PowerShell.Utility\Write-Warning 'AI did not return a valid command to execute.'
            return
        }

        if ($EnforceWhitelist) {
            $match = [regex]::Match($suggestedCmd, '^\s*(?<Command>[A-Za-z0-9\-]+)')
            if (-not $match.Success) {
                Microsoft.PowerShell.Utility\Write-Warning 'AI returned a command that could not be parsed for safety validation.'
                if (Microsoft.PowerShell.Management\Get-Command -Name 'GenXdev\Write-SecurityAuditLog' -ErrorAction SilentlyContinue) {
                    GenXdev\Write-SecurityAuditLog -EventType CommandBlocked -Description 'AI-generated command blocked: could not parse command name' -Details @{ Command = $suggestedCmd }
                }
                return
            }

            $cmdName = $match.Groups['Command'].Value
            $allowed = $false
            foreach ($pattern in $safeCommandWhitelist) {
                if ($cmdName -like $pattern) {
                    $allowed = $true
                    break
                }
            }

            if (-not $allowed) {
                Microsoft.PowerShell.Utility\Write-Host "`n" -ForegroundColor Red
                Microsoft.PowerShell.Utility\Write-Host '🔒 SECURITY BLOCK 🔒' -ForegroundColor Red
                Microsoft.PowerShell.Utility\Write-Host "The AI suggested a command that is not on the safe execution whitelist:" -ForegroundColor Yellow
                Microsoft.PowerShell.Utility\Write-Host "  Command: $cmdName" -ForegroundColor Cyan
                Microsoft.PowerShell.Utility\Write-Host "  Full: $suggestedCmd" -ForegroundColor Cyan
                Microsoft.PowerShell.Utility\Write-Host "`nReason: only read-only, non-destructive cmdlets are allowed by default." -ForegroundColor Yellow
                Microsoft.PowerShell.Utility\Write-Host 'To override this safety check, use -EnforceWhitelist $false (not recommended).' -ForegroundColor Yellow

                if (Microsoft.PowerShell.Management\Get-Command -Name 'GenXdev\Write-SecurityAuditLog' -ErrorAction SilentlyContinue) {
                    GenXdev\Write-SecurityAuditLog -EventType CommandBlocked -Description 'AI-generated command blocked by whitelist' -Details @{ Command = $suggestedCmd; CommandName = $cmdName }
                }

                return
            }
        }

        $yellow = "`e[33m"
        $cyan = "`e[36m"
        $reset = "`e[0m"

        $userChoice = $host.ui.PromptForChoice(
            'Are you sure you want to perform this action?',
            @"
--
$yellow$suggestedCmd$reset
--
$cyan$explanation$reset
--
"@, @('&No', '&Yes'), 1
        )

        if ($userChoice -eq 0) {
            return
        }

        if (Microsoft.PowerShell.Management\Get-Command -Name 'GenXdev\Write-SecurityAuditLog' -ErrorAction SilentlyContinue) {
            GenXdev\Write-SecurityAuditLog -EventType CommandGenerated -Description 'AI-generated command approved for execution' -Details @{ Command = $suggestedCmd; Model = $Model }
        }

        try {
            # Use ScriptBlock instead of Invoke-Expression for a safer execution path
            $safeScript = [System.Management.Automation.ScriptBlock]::Create($suggestedCmd)
            & $safeScript
        }
        catch {
            Microsoft.PowerShell.Utility\Write-Error "Command execution failed: $_"
            if (Microsoft.PowerShell.Management\Get-Command -Name 'GenXdev\Write-SecurityAuditLog' -ErrorAction SilentlyContinue) {
                GenXdev\Write-SecurityAuditLog -EventType CommandFailed -Description 'AI-generated command execution failed' -Details @{ Command = $suggestedCmd; Error = $_.Exception.Message }
            }
        }
    }

    end {
    }
}
###############################################################################
