#
# Module manifest for module 'GenXdev'
#
# Generated by: genXdev
#
# Generated on: 26/08/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GenXdev.psm1'

# Version number of this module.
ModuleVersion = '3.35.0'

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module
GUID = '2f62080f-0483-4421-8497-b3d433b65173'

# Author of this module
Author = 'genXdev'

# Company or vendor of this module
CompanyName = 'GenXdev'

# Copyright statement for this module
Copyright = 'Copyright 2021-2026 GenXdev'

# Description of the functionality provided by this module
Description = 'An all-in-one PowerShell toolkit combining AI, browser automation, media control, databases, and Windows utilities into one module.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.5.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
ClrVersion = '10.0.9'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'PackageManagement'; ModuleVersion = '1.4.8.1'; }, 
               @{ModuleName = 'Microsoft.WinGet.Client'; ModuleVersion = '1.29.280'; }, 
               @{ModuleName = 'Microsoft.PowerShell.ConsoleGuiTools'; ModuleVersion = '0.7.7'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'lib\GenXdev.dll', 'lib\WpfScreenHelper.dll', 
               'lib\Spectre.Console.dll', 'lib\Spectre.Console.Ansi.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = 'AfterInstall.ps1'

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'GenXdev.FileSystem.format.ps1xml', 
               'GenXdevCmdletInfo.format.ps1xml', 
               'ImageSearchResult.format.ps1xml', 'RefactorSet.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('lib\GenXdev.dll')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-ArrayTemplate', 'Add-EmoticonsToText', 'Add-FeatureLineToREADME', 
               'Add-IdeaLineToREADME', 'Add-IssueLineToREADME', 'Add-LineToREADME', 
               'Add-ReleaseNoteLineToREADME', 'Add-TodoLineToREADME', 
               'Add-WireGuardPeer', 'alignScript', 'Approve-NewTextFileContent', 
               'Assert-GenXdevCmdlet', 'Assert-GenXdevCmdletTests', 
               'Assert-GenXdevTest', 'Assert-ModuleDefinition', 
               'Assert-RefactorFile', 'Backup-CompletedFeatures', 
               'Backup-CompletedIdeas', 'Backup-CompletedIssues', 
               'Backup-CompletedReleaseNotes', 'Backup-CompletedTodoos', 
               'Backup-READMESections', 'Close-Webbrowser', 'Close-WebbrowserTab', 
               'Compare-ImageFaces', 'Confirm-InstallationConsent', 
               'Connect-PlaywrightViaDebuggingPort', 'Convert-PhysicsUnit', 
               'ConvertFrom-CorporateSpeak', 'ConvertFrom-DiplomaticSpeak', 
               'ConvertTo-CorporateSpeak', 'ConvertTo-DiplomaticSpeak', 
               'ConvertTo-LLMOpenAIApiFunctionDefinition', 
               'Copy-FilesToDateFolder', 'Copy-PDFsFromGoogleQuery', 
               'CurrentUserHasElevatedRights', 'Enable-Screensaver', 'Ensure7Zip', 
               'EnsureCopilotKeyboardShortCut', 'EnsureDeepStack', 
               'EnsureDefaultGenXdevRefactors', 'EnsureDockerDesktop', 
               'EnsureFFMPEG', 'EnsureGenXdev', 'EnsureGithubCLI', 
               'EnsureNuGetAssembly', 'EnsurePaintNet', 'EnsurePester', 
               'EnsurePlaywright', 'EnsurePSTools', 'EnsureSQLiteStudio', 
               'EnsureSSMSInstalled', 'EnsureVSCode', 
               'EnsureWindowsMediaFeaturePack', 'EnsureWinMerge', 'EnsureWireGuard', 
               'Expand-Path', 'Export-BrowserBookmarks', 'Find-BrowserBookmark', 
               'Find-DuplicateFiles', 'Find-Image', 'GenerateMasonryLayoutHtml', 
               'Get-ActiveUser', 'Get-AIDefaultLLMSettings', 
               'Get-AIKnownFacesRootpath', 'Get-AILLMSettings', 
               'Get-BrowserBookmark', 'Get-CmdletMetaData', 'Get-Fallacy', 
               'Get-Features', 'Get-GenXDevCmdlet', 'Get-GenXDevModule', 
               'Get-GenXDevModuleInfo', 'Get-GenXDevNewModulesInOrderOfDependency', 
               'Get-Ideas', 'Get-ImageDetectedFaces', 'Get-ImageDetectedObjects', 
               'Get-ImageDetectedScenes', 'Get-ImageMetadata', 'Get-Issues', 
               'Get-JsonExampleFromSchema', 'Get-KnownFolderPath', 
               'Get-LLMJsonOutput', 'Get-MediaFileCreationDate', 
               'Get-ModuleCmdletMetaData', 'Get-PlaywrightSessionReference', 
               'Get-PowerShellRoot', 'Get-Refactor', 'Get-RegisteredFaces', 
               'Get-ReleaseNotes', 'Get-ScriptExecutionErrorFixPrompt', 
               'Get-SimularMovieTitles', 'Get-SQLiteSchema', 
               'Get-SQLiteTableColumnData', 'Get-SQLiteTableData', 
               'Get-SQLiteTables', 'Get-SQLiteTableSchema', 'Get-SQLiteTransaction', 
               'Get-SQLiteViewColumnData', 'Get-SQLiteViewData', 'Get-SQLiteViews', 
               'Get-SQLiteViewSchema', 'Get-SQLServerSchema', 
               'Get-SQLServerTableColumnData', 'Get-SQLServerTableData', 
               'Get-SQLServerTables', 'Get-SQLServerTableSchema', 
               'Get-SQLServerTransaction', 'Get-SQLServerViewColumnData', 
               'Get-SQLServerViewData', 'Get-SQLServerViews', 
               'Get-SQLServerViewSchema', 'Get-TextTranslation', 'Get-Todoos', 
               'Get-WebbrowserTabDomNodes', 'Get-WikipediaSummary', 
               'Get-WindowPosition', 'Get-WireGuardPeerQRCode', 'Get-WireGuardPeers', 
               'Get-WireGuardStatus', 'Import-BrowserBookmarks', 
               'Import-GenXdevBookmarkletMenu', 'Import-GenXdevModules', 
               'Initialize-ScheduledTaskScripts', 'Invoke-AILLMSettingsPrompt', 
               'Invoke-AIPowershellCommand', 'Invoke-CommandElevated', 
               'Invoke-CommandFromToolCall', 'Invoke-Fasti', 
               'Invoke-GenXdevPSFormatter', 'Invoke-GenXdevScriptAnalyzer', 
               'Invoke-ImageEnhancement', 'Invoke-ImageFacesUpdate', 
               'Invoke-ImageKeywordUpdate', 'Invoke-ImageMetadataUpdate', 
               'Invoke-ImageObjectsUpdate', 'Invoke-ImageScenesUpdate', 
               'Invoke-LLMBooleanEvaluation', 'Invoke-LLMQuery', 
               'Invoke-LLMStringListEvaluation', 'Invoke-LLMTextTransformation', 
               'Invoke-OnEachGenXdevModule', 'Invoke-QueryImageContent', 
               'Invoke-SpectreAsk', 'Invoke-SpectreConfirm', 'Invoke-SpectrePrompt', 
               'Invoke-SQLiteQuery', 'Invoke-SQLiteStudio', 'Invoke-SQLServerQuery', 
               'Invoke-SSMS', 'Invoke-WebbrowserEvaluation', 'Invoke-WindowsUpdate', 
               'Invoke-WinMerge', 'Merge-TranslationCache', 'Move-FilesToDateFolder', 
               'New-GenXdevMCPToken', 'New-LLMAudioChat', 'New-LLMTextChat', 
               'New-MicrosoftShellTab', 'New-ModuleMarkdownHelp', 
               'New-ModuleXmlHelp', 'New-Refactor', 'New-SQLiteDatabase', 
               'New-SQLServerDatabase', 'Now', 'Open-AllPossibleQueries', 
               'Open-BingCopilotQuery', 'Open-BingQuery', 'Open-BrowserBookmarks', 
               'Open-BuiltWithSiteInfo', 'Open-ChatGPTQuery', 'Open-CloudLLMChat', 
               'Open-DeepSearchQuery', 'Open-GameOfLife', 'Open-GenXdevAppCatalog', 
               'Open-GithubCopilotQuery', 'Open-GithubQuery', 
               'Open-GoogleGeminiQuery', 'Open-GoogleQuery', 'Open-GoogleSiteInfo', 
               'Open-GrokipediaQuery', 'Open-IMDBQuery', 
               'Open-InstantStreetViewQuery', 'Open-MediaFile', 'Open-MovieQuote', 
               'Open-PlayWrightBrowser', 'Open-SearchEngine', 
               'Open-SimularWebSiteInfo', 'Open-SourceFileInIde', 
               'Open-StackOverflowQuery', 'Open-Timeline', 'Open-ViralSimulation', 
               'Open-VlcMediaPlayer', 'Open-VlcMediaPlayerLyrics', 
               'Open-WaybackMachineSiteInfo', 'Open-Webbrowser', 
               'Open-WebbrowserSideBySide', 'Open-WebsiteAndPerformQuery', 
               'Open-WhoisHostSiteInfo', 'Open-WikipediaNLQuery', 
               'Open-WikipediaQuery', 'Open-WolframAlphaQuery', 'Open-XGrokQuery', 
               'Open-Yab', 'Open-YabAIBattle', 'Open-YoutubeQuery', 'Out-Serial', 
               'PermanentlyDeleteGitFolders', 'Pop-Window', 
               'Publish-ReleaseNotesToManifest', 'Push-Window', 'ReadJsonWithRetry', 
               'Register-AllFaces', 'Register-Face', 'Remove-AllItems', 
               'Remove-DoubleEmptyLines', 'Remove-ImageMetaData', 
               'Remove-ItemWithFallback', 'Remove-Refactor', 'Remove-WireGuardPeer', 
               'Rename-InProject', 'Reset-WireGuardConfiguration', 
               'resetdefaultmonitor', 'ResolveInputObjectFileNames', 
               'Resume-TextToSpeech', 'Resume-WebbrowserTabVideo', 
               'Save-FoundImageFaces', 'Save-Transcriptions', 'SayDate', 'SayTime', 
               'Search-GenXdevCmdlet', 'secondscreen', 'Select-WebbrowserTab', 
               'Send-Key', 'Send-WakeOnLan', 'Set-AIKnownFacesRootpath', 
               'Set-AILLMSettings', 'Set-AIMetaLanguage', 
               'Set-BrowserVideoFullscreen', 'Set-ClipboardFiles', 
               'Set-FoundLocation', 'Set-GenXdevCommandNotFoundAction', 
               'Set-KnownFolderPath', 'Set-TaskbarAlignment', 'Set-VLCPlayerFocused', 
               'Set-WebbrowserTabLocation', 'Set-WindowPosition', 
               'Set-WindowPositionForSecondary', 'Show-ExceptionPanel', 
               'Show-FoundImagesInBrowser', 'Show-GenXdevCmdlet', 
               'Show-GenXdevCmdLetInIde', 'Show-Verb', 'Show-WebsiteInAllBrowsers', 
               'sidebyside', 'StabilizeVideo', 'Start-AudioTranscription', 
               'Start-GenXdevMCPServer', 'Start-NextRefactor', 'Start-RoboCopy', 
               'Start-SnakeGame', 'Start-TextToSpeech', 
               'Start-VlcMediaPlayerNextInPlaylist', 
               'Start-VlcMediaPlayerPreviousInPlaylist', 'Stop-TextToSpeech', 
               'Stop-WebbrowserVideos', 'Suspend-TextToSpeech', 
               'Switch-VlcMediaPlayerMute', 'Switch-VLCMediaPlayerPaused', 
               'Switch-VlcMediaPlayerRepeat', 'Test-DeepLinkImageFile', 
               'Test-RefactorLLMSelection', 'Unprotect-WebbrowserTab', 
               'Unregister-AllFaces', 'Unregister-Face', 'Update-AllImageMetaData', 
               'Update-Environment', 'Update-Refactor', 'UtcNow', 'VSCode', 
               'Write-SpectreLine', 'Write-SpectreMarkupLine', 'WriteFileOutput'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Convert-DotNetTypeToLLMType', 'ConvertTo-HashTable', 
               'ConvertTo-Uris', 'Copy-IdenticalParamValues', 'Find-Item', 
               'Get-AIMetaLanguage', 'Get-ApparentSizeAtArmLength', 
               'Get-AtEyeLengthSizeInMM', 'Get-AudioDeviceNames', 
               'Get-BCP47LanguageDictionary', 
               'Get-BuoyantForceByDisplacedVolumeAndDensity', 
               'Get-CentripetalAccelerationByVelocityAndRadius', 
               'Get-ChildProcesses', 'Get-ClipboardFiles', 'Get-CpuCore', 
               'Get-CurrentFocusedProcess', 'Get-DefaultWebbrowser', 
               'Get-DefaultWebLanguage', 'Get-DesktopScalingFactor', 
               'Get-DopplerFrequencyShiftBySourceSpeedAndObserverSpeed', 
               'Get-DragForceByVelocityDensityAreaAndCoefficient', 
               'Get-EscapeVelocityByMassAndRadius', 'Get-ForegroundWindow', 
               'Get-FreeFallDistance', 'Get-FreeFallHeight', 'Get-FreeFallTime', 
               'Get-GenXdevPreference', 'Get-GenXdevPreferenceNames', 
               'Get-GenXdevPreferencesDatabasePath', 'Get-GitChangedFiles', 
               'Get-HasCapableGpu', 'Get-ImageGeolocation', 
               'Get-ImpactVelocityByHeightAndGravity', 'Get-IsSpeaking', 
               'Get-KeyValueStoreNames', 'Get-KeyValueStorePath', 
               'Get-KineticEnergyByMassAndVelocity', 
               'Get-LightTravelTimeByDistance', 
               'Get-MagnificationByObjectDistanceAndImageDistance', 
               'Get-MomentumByMassAndVelocity', 'Get-MonitorCount', 
               'Get-MpCmdRunPath', 'Get-NextAffirmation', 'Get-NumberOfCpuCores', 
               'Get-OrbitalVelocityByRadiusAndMass', 
               'Get-PlaywrightProfileDirectory', 
               'Get-PotentialEnergyByMassHeightAndGravity', 
               'Get-PowershellMainWindow', 'Get-PowershellMainWindowProcess', 
               'Get-ProjectileRangeByInitialSpeedAndAngle', 'Get-RefactorReport', 
               'Get-RefractionAngleByIncidentAngleAndIndices', 
               'Get-ResonantFrequencyByLengthAndSpeed', 
               'Get-SoundTravelDistanceByTime', 'Get-SpeechToText', 'Get-StoreKeys', 
               'Get-TerminalVelocityByMassGravityDensityAndArea', 
               'Get-TimeOfFlightByInitialVelocityAndAngle', 
               'Get-ValueByKeyFromStore', 'Get-VectorSimilarity', 
               'Get-WaveSpeedByFrequencyAndWavelength', 'Get-Webbrowser', 
               'Get-WebLanguageDictionary', 'Get-Window', 'Initialize-SearchPaths', 
               'Move-ItemWithTracking', 'Move-ToRecycleBin', 'New-GitCommit', 
               'Receive-RealTimeSpeechToText', 'Remove-GenXdevPreference', 
               'Remove-JSONComments', 'Remove-KeyFromStore', 'Remove-KeyValueStore', 
               'Remove-OnReboot', 'Save-DesktopScreenShot', 'Set-ForegroundWindow', 
               'Set-GenXdevDefaultPreference', 'Set-GenXdevPreference', 
               'Set-GenXdevPreferencesDatabasePath', 'Set-LocationParent', 
               'Set-LocationParent2', 'Set-LocationParent3', 'Set-LocationParent4', 
               'Set-LocationParent5', 'Set-MonitorPowerOff', 'Set-MonitorPowerOn', 
               'Set-ValueByKeyInStore', 'Set-WindowsWallpaper', 
               'Start-ProcessElevated', 'Start-ProcessWithPriority', 'Test-CpuAvx', 
               'Test-PathUsingWindowsDefender', 'Test-UnattendedMode', 
               'Write-FileAtomic', 'Write-JsonFileAtomic', 'Write-TextFileAtomic'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '..', '...', '....', '.....', '......', 'aibc', 'aicgpt', 'aideepseek', 'aigc', 
               'aigg', 'aixg', 'appcatalog', 'archive-features', 'archive-ideas', 
               'archive-issues', 'archive-readme-sections', 'archive-releasenotes', 
               'archive-todoos', 'ask', 'askchatgpt', 'askdeepsearch', 'askgemini', 
               'askghcopilot', 'askxgrok', 'bookmarks', 'bq', 'CloseTab', 'cmdlet', 'cmds', 
               'commit', 'comparefaces', 'conway', 'corporatize', 'ct', 'diplomatize', 
               'dispicetext', 'editcmdlet', 'editcode', 'emojify', 'enhanceimage', 'ep', 
               'equalstrue', 'et', 'Eval', 'fasti', 'fdf', 'feature', 'features', 'findimages', 
               'findmedia', 'folder', 'foreach-genxdev-module-do', 'FormatArray', 
               'fsvideo', 'fvlc', 'gameoflife', 'gbm', 'gcbf', 'gcmds', 'getclipfiles', 
               'getfixprompt', 'getimgmetalang', 'getkeys', 'getlist', 'getPreference', 
               'getPreferenceNames', 'getsqltx', 'getstorenames', 'getstring', 
               'getvalue', 'gitchanged', 'gusers', 'gwp', 'HasNoVirus', 'hint', 'idea', 
               'ideas', 'imagekeywordgeneration', 'imageobjectdetection', 
               'imagepeopledetection', 'imagepropdetection', 'imagescenedetection', 
               'imdb', 'improvecmdlet', 'improvecmdlettests', 'invokekeys', 'iss', 'issue', 
               'issues', 'isv', 'l', 'lcd', 'li', 'llm', 'llmaudiochat', 'llmchat', 'llmset', 
               'llmsettings', 'lt', 'media', 'monitoroff', 'moviequote', 'Nav', 
               'newrefactor', 'newsqltx', 'nextrefactor', 'nice', 'nsqldb', 'owaq', 
               'pausespeech', 'popw', 'poweroff', 'promptllmsettings', 'pubrelnotes', 
               'pushw', 'q', 'qalpha', 'qgh', 'qgithub', 'qllm', 'qq', 'qso', 'rc', 
               'refactorreport', 'refactors', 'releasenote', 'releasenotes', 
               'reloadgenxdev', 'removeimagedata', 'removekey', 'removePreference', 
               'resumespeech', 'rip', 'rmf', 'rungenxdevtests', 'saveimagefaces', 'say', 
               'scbf', 'sdel', 'searchcmdlet', 'sendkeys', 'setclipfiles', 'setPreference', 
               'setPreferenceDefault', 'setvalue', 'showfoundimages', 'showverbs', 
               'showvlc', 'simularsite', 'sites', 'snake', 'spb', 'spellcheck', 
               'sqlservermanagementstudio', 'ssms', 'ssst', 'sst', 'st', 'timeline', 'todo', 
               'todoos', 'transcribe', 'transcribefile', 'translate', 'uncorporatize', 
               'undiplomatize', 'updateallimages', 'UpdateFaces', 'updaterefactor', 
               'updatewindows', 'viral', 'virusscan', 'vlc', 'vlcback', 'vlcf', 'vlclyrics', 
               'vlcmedia', 'vlcmute', 'vlcnext', 'vlcpause', 'vlcplay', 'vlcprev', 
               'vlcrepeat', 'vlcunmute', 'wakemonitor', 'wayback', 'wb', 'wbc', 'wbctrl', 
               'wbn', 'wbsst', 'wbvideoplay', 'wbvideostop', 'WhatAboutIt', 'whois', 'wiki', 
               'wikinl', 'wikipedia', 'wikitxt', 'wl', 'wp', 'wps', 'x', 'xc', 'yab', 'yabbattle', 
               'youtube'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @('GenXdev')

# List of all files packaged with this module
FileList = 'Afterinstall.ps1', 'cmdlets-meta.json', 'default-llmproviders.json', 
               'favicon.ico', 'GenXdev.FileSystem.format.ps1xml', 'GenXdev.psd1', 
               'GenXdev.psm1', 'GenXdevCmdletInfo.format.ps1xml', 
               'ImageSearchResult.format.ps1xml', 'LICENSE', 'masonary.html', 
               'PSScriptAnalyzerSettings.psd1', 
               'recommended-aitoolset-cmdlets.txt', 'RefactorSet.format.ps1xml', 
               'Assets\agents md.asset.txt', 
               'Assets\Microsoft.PowerShell.Debug_profile.ps1.asset.txt', 
               'Assets\Microsoft.PowerShell_profile.ps1.asset.txt', 
               'Assets\powershell.jpg.asset.txt', 'Assets\README.md.asset.txt', 
               'en-US\GenXdev-help.xml', 'en-US\GenXdev.dll-Help.xml', 
               'lib\EdgeTTS.DotNet.dll', 'lib\e_sqlite3.dll', 
               'lib\GenXdev.deps.json', 'lib\GenXdev.dll', 'lib\ggml-base.dll', 
               'lib\ggml-cpu.dll', 'lib\ggml.dll', 'lib\hostpolicy.dll', 
               'lib\Microsoft.Data.SqlClient.dll', 'lib\msvcp140.dll', 
               'lib\NAudio.Asio.dll', 'lib\NAudio.Core.dll', 'lib\NAudio.dll', 
               'lib\NAudio.Dmo.dll', 'lib\NAudio.Midi.dll', 'lib\NAudio.Wasapi.dll', 
               'lib\NAudio.WinForms.dll', 'lib\NAudio.WinMM.dll', 
               'lib\Spectre.Console.Ansi.dll', 'lib\Spectre.Console.dll', 
               'lib\System.Numerics.Tensors.dll', 'lib\vcomp140.dll', 
               'lib\vcruntime140.dll', 'lib\vcruntime140_1.dll', 'lib\whisper.dll', 
               'lib\WpfScreenHelper.dll', 
               'Assets\.github\copilot-instructions.md.asset.txt', 
               'Assets\.vscode\extensions.json.asset.txt', 
               'Assets\.vscode\launch.json.asset.txt', 
               'Assets\.vscode\mcp.json.asset.txt', 
               'Assets\.vscode\settings.json.asset.txt', 
               'Assets\.vscode\tasks.json.asset.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-AddInstallationConsentPrompt-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-AddInstallationConsentPrompt.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-AddProgressSupport-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-AddProgressSupport.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-CheckAllRequirements-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-CheckAllRequirements.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-CheckCSharpInvocations.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ConvertToCSharp.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-CreateUnitTests.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-FailedScriptAnalyzerResults-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-FailedScriptAnalyzerResults.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-FixIntrusiveOutput-Script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-FixIntrusiveOutput.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ImproveUnitTest.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ModuleDefinition.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-New-GenXdevCmdlet.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-NewGenXdevCmdLet-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-NewGenXdevCmdLet.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-OnlyCSharpDocumentation.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-OnlyDocumentation-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-OnlyDocumentation.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ParameterSplatting-scripts.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ParameterSplatting.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-PSExceptionHandling-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-PSExceptionHandling.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-PSFindIntrusiveOutput-script.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-PSFindIntrusiveOutput.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ResolveFailedTest-sccript.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-ResolveFailedTest.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-StandardRequirements.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-UnsafePathUsage-scripts.txt', 
               'Prompts\GenXdev.Coding.PowerShell.Modules\Assert-UnsafePathUsage.txt', 
               'Assets\Modules\GenXdev.Local\3.33.0\GenXdev.Local.psd1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.33.0\GenXdev.Local.psm1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.33.0\powershell.jpg.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.33.0\README.md.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.34.0\GenXdev.Local.psd1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.34.0\GenXdev.Local.psm1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.34.0\powershell.jpg.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.34.0\README.md.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.35.0\GenXdev.Local.psd1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.35.0\GenXdev.Local.psm1.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.35.0\powershell.jpg.asset.txt', 
               'Assets\Modules\GenXdev.Local\3.35.0\README.md.asset.txt'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'GenXdev'

        # A URL to the license for this module.
        LicenseUri = 'https://www.gnu.org/licenses/gpl-3.0.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://powershell.genxdev.net/#GenXdev'

        # A URL to an icon representing this module.
        IconUri = 'https://genxdev.net/favicon.ico'

        # ReleaseNotes of this module
        ReleaseNotes = 'Updated NAudio to version 3
Dropped Whisper.Net for native
Fixed: Rename-InProject didn''t write changed files to disk when only capitalization changed
Improved: Error message for Invoke-LLMQuery when endpoint cannot be reached
Fixed: Exception during launch of console snake game
Fixed: Some no-verb cmdlets where excluded from deployment'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $true

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

